server:
  port: 8080

spring:
    datasource:
        name: test
        url: jdbc:mysql://120.79.227.127:3306/clothes
        username: remote
        password: tmzzxy1997
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.demo.model

jwt:
  header: "Authorization"
  secret: "mySecret"
  expiration: 60480000
  type: "Bearer"
  route:
    auth:
      login: "/auth/login"
      register: "/auth/register"
      refresh: "/auth/refresh"
    topic:
      list: "/topic/list"
      id: "/topic/id"
    news:
      list: "/news/list"
    user:
      list: "/user/list"


##pagehelper分页插件
#pagehelper:
#    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql